/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

/**
 *
 * @author Dany_Hernandez
 */
public class FrmFicha extends javax.swing.JFrame {

    /**
     * Creates new form FrmFicha
     */
    public FrmFicha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelEncabezado = new javax.swing.JPanel();
        scpInformacion = new javax.swing.JScrollPane();
        panelPrincipal = new javax.swing.JPanel();
        panelInfoPersonal = new javax.swing.JPanel();
        panelInstitucion = new javax.swing.JPanel();
        panelFoto = new javax.swing.JPanel();
        panelEstadoCivil = new javax.swing.JPanel();
        panelContacto = new javax.swing.JPanel();
        panelLugarNacimiento = new javax.swing.JPanel();
        panelContactoPersonal = new javax.swing.JPanel();
        panelInfoAcademica1 = new javax.swing.JPanel();
        panelInfoAcemica2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelOtraInformacion = new javax.swing.JPanel();
        scpTextArea = new javax.swing.JScrollPane();
        txaNota = new javax.swing.JTextArea();
        panelControles = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        getContentPane().add(panelEncabezado, java.awt.BorderLayout.NORTH);

        scpInformacion.setBackground(new java.awt.Color(153, 153, 255));

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        panelInfoPersonal.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout panelInfoPersonalLayout = new javax.swing.GroupLayout(panelInfoPersonal);
        panelInfoPersonal.setLayout(panelInfoPersonalLayout);
        panelInfoPersonalLayout.setHorizontalGroup(
            panelInfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInfoPersonalLayout.setVerticalGroup(
            panelInfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelInfoPersonal, gridBagConstraints);

        panelInstitucion.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout panelInstitucionLayout = new javax.swing.GroupLayout(panelInstitucion);
        panelInstitucion.setLayout(panelInstitucionLayout);
        panelInstitucionLayout.setHorizontalGroup(
            panelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInstitucionLayout.setVerticalGroup(
            panelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelInstitucion, gridBagConstraints);

        panelFoto.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout panelFotoLayout = new javax.swing.GroupLayout(panelFoto);
        panelFoto.setLayout(panelFotoLayout);
        panelFotoLayout.setHorizontalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelFotoLayout.setVerticalGroup(
            panelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelFoto, gridBagConstraints);

        panelEstadoCivil.setBackground(new java.awt.Color(255, 102, 204));

        javax.swing.GroupLayout panelEstadoCivilLayout = new javax.swing.GroupLayout(panelEstadoCivil);
        panelEstadoCivil.setLayout(panelEstadoCivilLayout);
        panelEstadoCivilLayout.setHorizontalGroup(
            panelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelEstadoCivilLayout.setVerticalGroup(
            panelEstadoCivilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelEstadoCivil, gridBagConstraints);

        panelContacto.setBackground(new java.awt.Color(204, 153, 255));

        javax.swing.GroupLayout panelContactoLayout = new javax.swing.GroupLayout(panelContacto);
        panelContacto.setLayout(panelContactoLayout);
        panelContactoLayout.setHorizontalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContactoLayout.setVerticalGroup(
            panelContactoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelContacto, gridBagConstraints);

        panelLugarNacimiento.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout panelLugarNacimientoLayout = new javax.swing.GroupLayout(panelLugarNacimiento);
        panelLugarNacimiento.setLayout(panelLugarNacimientoLayout);
        panelLugarNacimientoLayout.setHorizontalGroup(
            panelLugarNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLugarNacimientoLayout.setVerticalGroup(
            panelLugarNacimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelLugarNacimiento, gridBagConstraints);

        panelContactoPersonal.setBackground(new java.awt.Color(255, 255, 153));

        javax.swing.GroupLayout panelContactoPersonalLayout = new javax.swing.GroupLayout(panelContactoPersonal);
        panelContactoPersonal.setLayout(panelContactoPersonalLayout);
        panelContactoPersonalLayout.setHorizontalGroup(
            panelContactoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelContactoPersonalLayout.setVerticalGroup(
            panelContactoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelContactoPersonal, gridBagConstraints);

        panelInfoAcademica1.setBackground(new java.awt.Color(51, 51, 255));

        javax.swing.GroupLayout panelInfoAcademica1Layout = new javax.swing.GroupLayout(panelInfoAcademica1);
        panelInfoAcademica1.setLayout(panelInfoAcademica1Layout);
        panelInfoAcademica1Layout.setHorizontalGroup(
            panelInfoAcademica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInfoAcademica1Layout.setVerticalGroup(
            panelInfoAcademica1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelInfoAcademica1, gridBagConstraints);

        panelInfoAcemica2.setBackground(new java.awt.Color(51, 255, 153));

        javax.swing.GroupLayout panelInfoAcemica2Layout = new javax.swing.GroupLayout(panelInfoAcemica2);
        panelInfoAcemica2.setLayout(panelInfoAcemica2Layout);
        panelInfoAcemica2Layout.setHorizontalGroup(
            panelInfoAcemica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelInfoAcemica2Layout.setVerticalGroup(
            panelInfoAcemica2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelInfoAcemica2, gridBagConstraints);

        jLabel1.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelPrincipal.add(jLabel1, gridBagConstraints);

        jLabel2.setText("jLabel2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 28;
        gridBagConstraints.gridwidth = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelPrincipal.add(jLabel2, gridBagConstraints);

        panelOtraInformacion.setBackground(new java.awt.Color(153, 153, 0));

        javax.swing.GroupLayout panelOtraInformacionLayout = new javax.swing.GroupLayout(panelOtraInformacion);
        panelOtraInformacion.setLayout(panelOtraInformacionLayout);
        panelOtraInformacionLayout.setHorizontalGroup(
            panelOtraInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelOtraInformacionLayout.setVerticalGroup(
            panelOtraInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 30;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(panelOtraInformacion, gridBagConstraints);

        txaNota.setColumns(20);
        txaNota.setRows(5);
        scpTextArea.setViewportView(txaNota);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 34;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        panelPrincipal.add(scpTextArea, gridBagConstraints);

        scpInformacion.setViewportView(panelPrincipal);

        getContentPane().add(scpInformacion, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelControlesLayout = new javax.swing.GroupLayout(panelControles);
        panelControles.setLayout(panelControlesLayout);
        panelControlesLayout.setHorizontalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 475, Short.MAX_VALUE)
        );
        panelControlesLayout.setVerticalGroup(
            panelControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        getContentPane().add(panelControles, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFicha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFicha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelContacto;
    private javax.swing.JPanel panelContactoPersonal;
    private javax.swing.JPanel panelControles;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JPanel panelEstadoCivil;
    private javax.swing.JPanel panelFoto;
    private javax.swing.JPanel panelInfoAcademica1;
    private javax.swing.JPanel panelInfoAcemica2;
    private javax.swing.JPanel panelInfoPersonal;
    private javax.swing.JPanel panelInstitucion;
    private javax.swing.JPanel panelLugarNacimiento;
    private javax.swing.JPanel panelOtraInformacion;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane scpInformacion;
    private javax.swing.JScrollPane scpTextArea;
    private javax.swing.JTextArea txaNota;
    // End of variables declaration//GEN-END:variables
}
